### ISSUE TITLE
Output cubes contain only zeros (on galaxy)

### ISSUE THREAD

**Issue by gheald** [sarrvesh/cuFFS#37]
I've tried using the program both on MWA and ASKAP data, and in both cases the pixel values in the output cubes contain only zeros. The program seems to complete successfully, and the cubes are valid FITS files, but they don't contain any useful data. Unsure whether this is due to the build that I managed to do on galaxy, or the code itself. Did you ever see something like this on other systems?

**Comment by AlecThomson** [comment]
I've just ran into the same issue with GMIMS data using a build on an ANU server. Again the output was a FITS cube of the correct shape but made entirely of 0s.

**Comment by gheald** [comment]
I just discovered that my fresh build on Bracewell also produces a cube containing just zeros! This is puzzling.

**Comment by sarrvesh** [comment]
@AlecThomson To help troubleshoot this issue, can you let me know if you are using the latest release v0.5? @gheald I presume this is while operating in the FITS mode, is that correct?

**Comment by gheald** [comment]
My most recent result was actually after running in HDFITS mode. The initial problem (as seen on galaxy) would definitely have been in FITS mode.

**Comment by AlecThomson** [comment]
@sarrvesh - Yep, I was using the latest version. My test was with rotated (frequency first) FITS cubes.

**Comment by sarrvesh** [comment]
I don't suppose this bug is still in the code. I'll close this issue. Please reopen if necessary.
